image: "node:latest"

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

before_script:
  - npx npm-merge-driver install --global
  - npm install

stages:
  - test

lint:
  stage: test
  script:
    - npm run lint

test:
  stage: test
  script:
    - npm run test
